+++
title = "never"
author = ["Yasuhito Takamiya"]
date = 2021-03-18T00:00:00+09:00
draft = false
+++

[SRS の回答方式による効果の違い]({{< relref "20210319113717-srs_の回答方式による効果の違い" >}})を確認するために、[Execute Program]({{< relref "20210302155222-execute_program" >}}) のレッスン [never](https://www.executeprogram.com/courses/typescript/lessons/never) を元に Anki カードを起こしてみる。

---

関数の中には、決して戻らないものがあります。例えば、常に例外を発生させる関数は決して戻りません。

```typescript
function throws() {
  throw new Error('oh no');
}
throws();

// 結果
// Error: oh no
```

この関数の戻り値の型はどうすればよいでしょうか？ TypeScript は、この関数の戻り値の型を `void` と推測します。しかし、それでは何が起こっているのか完全には把握できていません。

`void` 型は、何らかの処理を行い終了するが、値を返さない関数のための型です。上の関数はこれとは異なり、この関数を呼び出しても、その後のコードは全く実行されません。

幸いなことに、TypeScript にはそのための型があります: `never` です。

```typescript
function throws(): never {
  throw new Error('oh no');
}
throws();

// 結果
// Error: oh no
```

`never` 型はちょっと不思議です。他のどの型にも割り当て可能です[^fn:1]。例えば、 `number` 型の変数に割り当てることができます。この関数は今まで通りに例外を投げますので、結果は上と同じです。

```typescript
function throws(): never {
  throw new Error('oh no');
}
const n: number = throws();

// 結果
// Error: oh no
```

最初は、 `never` が `any` のように振る舞っているように見えます。なぜなら、 `never` を `number` （または `string` 、その他何でも）に割り当てることができるからです。しかし、 `any` と違って、これは安全です。

コンパイラは `throws` 関数が決して戻らないことを知っているので、変数 `n` には何も代入されないことも知っています。型は実行時にデータが正しいことを保証するために存在します。もし、実行時に代入が実際に行われることがなく、コンパイラが事前にそのことを確実に知っているのであれば、型は重要ではありません。

しかし、 `never` に他の型を割り当てることはできません。そうすると、 `never` のルールである「実際に値を保持することはない」を破ってしまいます。 `never` に何らかの値を代入しようとすると、常に型エラーになります。

```typescript
const aNever: never = 5;
aNever;

// 結果
// type error: Type 'number' is not assignable to type 'never'.
```

絶対に `never` には何も割り当てられません。 `any` ですらも!

```typescript
const anAny: any = 5;
const aNever: never = anAny;
aNever;

// 結果
// type error: Type 'any' is not assignable to type 'never'.
```

関数が常に例外をスローするが、明示的な戻り値の型を持たない場合、TypeScript は戻り値の型を `void` と推測します。これは悪いことではありませんが、明示的に `never` とマークしたほうが、TypeScript にもう少し多くの情報を与えることができます。

例えば、ある関数が `never` を返す別の関数を呼び出したとします。TypeScript は外側の関数の型も `never` と正しく推論します。

```typescript
function throws(): never {
  throw new Error('oh no');
}

function alsoThrows() {
  return throws();
}

const n: number = alsoThrows();

// 結果
// Error: oh no
```

このコードがコンパイルされたことで、 `alsoThrows` の戻り値の型が `never` であることがわかりました。もし戻り値の型が `void` であれば、数値に割り当てることはできません。

次の関数の戻り値の型を `never` に変更します。そうすると型エラーが発生します。なぜなら、この関数は戻ります。TypeScript は `never` 関数が値を返すことを許可しません。

```typescript
function f(): number {
  return 5;
}
```

変更後

```typescript
function f(): never {
  return 5;
}

// 結果
// type error: Type 'number' is not assignable to type 'never'.
```

TypeScript では、 `never` 関数が条件付きで戻ることもできません（例: `if` の中）。関数が値を返す方法があるならば、その戻り値の型は `never` であってはならないのです。(この関数は型エラーを発生させます)

```typescript
function forcePositive(x: number): never {
  if (x > 0) {
    return x;
  } else {
    throw new Error('Number was negative!');
  }
}

// 結果
// type error: Type 'number' is not assignable to type 'never'.
```

`never` 型が適用されるのは、例外を発生させる関数だけではありません。例えば、無限ループを持つ関数は、 `never` 型の戻り値を持つことができます（そうすべきです！）。

残念ながら、ここではその動く実例を示すことはできません。なぜなら、それは決して終了しないからです。しかし、その逆の例を示すことはできます。つまり、無限ループのように見える関数で、絶対に終わらないと主張していますが、時々戻ってくることがあるようなものです。これは型エラーです。

```typescript
function f(): never {
  while (true) {
    if (Math.random() < 0.000001) {
      break;
    }
  }
}

// 結果
// type error: A function returning 'never' cannot have a reachable end point.
```

最後に、 `void` と `never` について簡単にまとめておきます。

`void` は、関数が最終的に終了して戻ることを意味します。ただ、何の値も返さないということです。関数には `return` 文がないか、または `return` 文の後に値がない状態になっています。 `void` 型は、値がないことを表すので、何にも代入できません。

`never` は、関数が決して正常に終了しないことを意味します。例外が発生したり、無限ループに陥ったりするかもしれません。Node のようなサーバーサイドのシステムであれば、 `process.exit()` を呼び出してプロセスを終了させるかもしれません。いずれにしても、実行が関数の最後に到達することはありません。 `never` 型は何にでも代入可能です。なぜならコンパイラは、実行時には実際には代入が行われないことを知っているからです。

[^fn:1]: `never` はすべての型のサブタイプ (派生型) であり、これをボトム型 (bottom type) と呼ぶ。つまり、他のすべての型に割り当てることができ、 `never` 型の値はどこでも安全に使えるという意味である。理論的な意味としては、ボトム型は値を持たない型としてとらえることができ、常に偽である数学的命題に相当する。
